id: 8
tag: 'MM130'
name: 'Marathon Match 130 - GraphLabeling'
category: 'TopCoder Marathon'

submissions_dir: ./data/submissions
seed_range: 1+100
tester: ./tester/tester.jar
source: /mnt/c/dev/heuristic/tasks/MM130/src/GraphLabeling.cpp
metric: min_div_yours
timelimit_ms: 10000
