id: 13
tag: 'AHC012'
name: 'AtCoder Heuristic Contest 012'
category: 'AHC'

submissions_dir: ./data/submissions
seed_range: 1+100
tester: ./tester/tester.jar
source: /mnt/c/Users/komori3/OneDrive/dev/compro/heuristic/tasks/MM139/src/PipeConnector.cpp
metric: yours_div_max
timelimit_ms: 10000
