id: 13
tag: 'AHC012'
name: 'AtCoder Heuristic Contest 012'
category: 'AHC'

submissions_dir: ./data/submissions
seed_list: ./tools/seeds.txt
input_dir: ./tools/in
judge: ./tools/target/release/vis
source: /mnt/c/Users/komori3/OneDrive/dev/compro/heuristic/tasks/AHC012/src/solver.cpp
metric: greater
timelimit_ms: 3000
