id: 1
tag: 'Chokudai003'
name: 'Chokudai Contest 003'
category: 'AtCoder Marathon'

submissions_dir: ./data/submissions
seed_file: ./data/seeds.txt
generator: ./src/build/generator
judge: ./src/build/judge
source: ./src/solvers/solver.cpp
metric: greater
timelimit_ms: 10000